# .github/workflows/nuxt-hub.yml
name: Deploy
on: push

jobs:
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command

      - name: Deploy site
        run: yarn deploy
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}