# .github/workflows/nuxt-hub.yml
name: Build and Push
on: push

jobs:
  deploy:
    name: "Build and Push"
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command

      - name: Build and Deploy
        run: |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action" 
            yarn force-deploy