# .github/workflows/nuxt-hub.yml
name: Deploy
on: push

jobs:
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command

      - name: Deploy site
        run: |
            gh auth login --with-token
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action" 
            yarn deploy
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}